language: node_js
node_js:
    - '8'
    - '9'
    - '10'
cache:
    directories:
        - 'node_modules'
        - .eslintcache
before_script:
    - npm run build
    - npm run lint
script:
    - npm run test:cov
    - npm install --global typedoc typescript
    - CURRENT_VERSION=$(npm run version --silent)
    - typedoc --out "ts-docs/$CURRENT_VERSION" src
    - touch ./ts-docs/.nojekyll
    - if [ "$TRAVIS_NODE_VERSION" = "8" ]; then npm run coveralls-report; fi
deploy:
    - provider: script
      skip_cleanup: true
      script: /bin/sh travis/github-pages.sh
      on:
          branch: master
          node_js: '9'
    - provider: script
      skip_cleanup: true
      script: /bin/sh travis/uploadArchives.sh
      on:
          branch: master
          node_js: '8'
    - provider: script
      skip_cleanup: true
      script: /bin/sh travis/release.sh
      on:
          branch: $RELEASE_BRANCH
          node_js: '8'
